"""ML layer: dataset construction, splits, LightGBM training, MLflow, predictions"""

from src.ml.dataset import (
    DEFAULT_AS_OF_DATE,
    DEFAULT_FEATURE_VERSION,
    build_category_encoders,
    build_engineered_feature_payload,
    build_model_training_data_query,
    build_model_training_record,
    calculate_ratio,
    derive_target_extreme_rainfall_event,
    encode_category,
    fetch_model_training_inputs,
    generate_model_training_records,
    persist_model_training_data,
    run_model_training_data_build,
    safe_log1p,
    validate_model_training_records,
)
from src.ml.evaluation import (
    build_feature_importance_frame,
    calculate_binary_classification_metrics,
    calculate_ranking_metrics,
)
from src.ml.prediction import (
    DEFAULT_MODEL_NAME as PREDICTION_DEFAULT_MODEL_NAME,
)
from src.ml.prediction import (
    DEFAULT_MODEL_VERSION as PREDICTION_DEFAULT_MODEL_VERSION,
)
from src.ml.prediction import (
    align_features_to_model,
    build_model_prediction_records,
    calculate_prediction_ranks,
    flatten_prediction_rows,
    generate_prediction_probabilities,
    infer_top_risk_driver,
    load_feature_importance,
    load_model_artifacts,
    load_prediction_rows,
    persist_model_predictions,
    run_batch_prediction,
    validate_model_prediction_records,
)
from src.ml.splits import assign_train_test_split, summarise_train_test_split
from src.ml.tracking import (
    configure_mlflow,
    get_mlflow_tracking_uri,
    log_training_run_to_mlflow,
)
from src.ml.training import (
    DEFAULT_MODEL_NAME,
    DEFAULT_MODEL_VERSION,
    TARGET_NAME,
    build_train_test_matrices,
    calculate_scale_pos_weight,
    flatten_training_rows,
    load_training_rows,
    run_lightgbm_training,
    save_training_artifacts,
    train_lightgbm_model,
)

__all__ = [
    "DEFAULT_AS_OF_DATE",
    "DEFAULT_FEATURE_VERSION",
    "DEFAULT_MODEL_NAME",
    "DEFAULT_MODEL_VERSION",
    "PREDICTION_DEFAULT_MODEL_NAME",
    "PREDICTION_DEFAULT_MODEL_VERSION",
    "TARGET_NAME",
    "align_features_to_model",
    "assign_train_test_split",
    "build_category_encoders",
    "build_engineered_feature_payload",
    "build_feature_importance_frame",
    "build_model_prediction_records",
    "build_model_training_data_query",
    "build_model_training_record",
    "build_train_test_matrices",
    "calculate_binary_classification_metrics",
    "calculate_prediction_ranks",
    "calculate_ranking_metrics",
    "calculate_ratio",
    "calculate_scale_pos_weight",
    "configure_mlflow",
    "derive_target_extreme_rainfall_event",
    "encode_category",
    "fetch_model_training_inputs",
    "flatten_prediction_rows",
    "flatten_training_rows",
    "generate_model_training_records",
    "generate_prediction_probabilities",
    "get_mlflow_tracking_uri",
    "infer_top_risk_driver",
    "load_feature_importance",
    "load_model_artifacts",
    "load_prediction_rows",
    "load_training_rows",
    "log_training_run_to_mlflow",
    "persist_model_predictions",
    "persist_model_training_data",
    "run_batch_prediction",
    "run_lightgbm_training",
    "run_model_training_data_build",
    "safe_log1p",
    "save_training_artifacts",
    "summarise_train_test_split",
    "train_lightgbm_model",
    "validate_model_prediction_records",
    "validate_model_training_records",
]
