"""Parametric insurance trigger evaluation and payout calculations"""

from src.insurance.payout import (
    build_payout_input_query,
    calculate_asset_payout_record,
    calculate_estimated_payout,
    calculate_payout_rate,
    calculate_trigger_status,
    ensure_default_simulation_run,
    fetch_payout_inputs,
    generate_payout_records,
    get_default_payout_thresholds,
    persist_payout_results,
    run_payout_simulation,
    validate_payout_records,
    validate_payout_thresholds,
)
from src.insurance.simulation import (
    build_simulation_id,
    build_threshold_config,
    calculate_portfolio_payout_summary,
    ensure_simulation_run,
    get_default_coverage_multiplier_scenarios,
    get_default_threshold_scenarios,
    run_combined_sensitivity,
    run_coverage_multiplier_sensitivity,
    run_single_simulation,
    run_threshold_sensitivity,
    validate_simulation_config,
)

__all__ = [
    "build_payout_input_query",
    "build_simulation_id",
    "build_threshold_config",
    "calculate_asset_payout_record",
    "calculate_estimated_payout",
    "calculate_payout_rate",
    "calculate_portfolio_payout_summary",
    "calculate_trigger_status",
    "ensure_default_simulation_run",
    "ensure_simulation_run",
    "fetch_payout_inputs",
    "generate_payout_records",
    "get_default_coverage_multiplier_scenarios",
    "get_default_payout_thresholds",
    "get_default_threshold_scenarios",
    "persist_payout_results",
    "run_combined_sensitivity",
    "run_coverage_multiplier_sensitivity",
    "run_payout_simulation",
    "run_single_simulation",
    "run_threshold_sensitivity",
    "validate_payout_records",
    "validate_payout_thresholds",
    "validate_simulation_config",
]
